# Generated by Django 4.1 on 2022-08-15 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_partner_remove_location_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField(max_length=10)),
                ('reservation', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.location')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
