# Generated by Django 4.1 on 2022-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_date_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
