# Generated by Django 4.1 on 2022-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_date_reservation_alter_date_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='budget',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
